/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalbs;
import java.sql.*;


/**
 *
 * @author rohit157
 */
public class Addempinfo extends javax.swing.JFrame {

    /**
     * Creates new form Addempinfo
     */
    public Addempinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        UseridField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JTextField();
        BackToLoginpage = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Addemp = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        removeId = new javax.swing.JTextField();
        RemoveEmp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        clearbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        SalaryField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee Information");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.orange, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setText("Address");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, -1));

        jLabel2.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Name       ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("User Id     ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, -1));

        jLabel4.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Password ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, -1));

        AddressField.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        AddressField.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 630, 40));

        NameField.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        NameField.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 630, 40));

        UseridField.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        UseridField.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(UseridField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 630, 40));

        PasswordField.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 630, 40));

        BackToLoginpage.setBackground(new java.awt.Color(51, 255, 255));
        BackToLoginpage.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        BackToLoginpage.setForeground(new java.awt.Color(0, 102, 102));
        BackToLoginpage.setText("Back To Login Page");
        BackToLoginpage.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 255)));
        BackToLoginpage.setFocusable(false);
        BackToLoginpage.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BackToLoginpage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BackToLoginpage.setVerifyInputWhenFocusTarget(false);
        BackToLoginpage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackToLoginpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginpageActionPerformed(evt);
            }
        });
        jPanel1.add(BackToLoginpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 210, 50));

        jLabel5.setFont(new java.awt.Font("NTR", 3, 18)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 620, 20));

        Addemp.setBackground(new java.awt.Color(51, 255, 255));
        Addemp.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Addemp.setForeground(new java.awt.Color(0, 102, 51));
        Addemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/empaddbutton.png"))); // NOI18N
        Addemp.setText("Add Employee");
        Addemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 255)));
        Addemp.setFocusable(false);
        Addemp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Addemp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Addemp.setVerifyInputWhenFocusTarget(false);
        Addemp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddempActionPerformed(evt);
            }
        });
        jPanel1.add(Addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 210, 50));

        BackButton.setBackground(new java.awt.Color(51, 255, 255));
        BackButton.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 51, 0));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/BackButtonimg.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 255)));
        BackButton.setFocusable(false);
        BackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BackButton.setVerifyInputWhenFocusTarget(false);
        BackButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 140, 50));

        jLabel6.setFont(new java.awt.Font("NTR", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Enter New Employee Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("NTR", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Remove Employee");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, -1, 40));

        jLabel8.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("Employee Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        removeId.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        removeId.setForeground(new java.awt.Color(255, 0, 51));
        removeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeIdActionPerformed(evt);
            }
        });
        jPanel1.add(removeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 650, 40));

        RemoveEmp.setBackground(new java.awt.Color(51, 255, 255));
        RemoveEmp.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        RemoveEmp.setForeground(new java.awt.Color(0, 153, 102));
        RemoveEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/empdelete.png"))); // NOI18N
        RemoveEmp.setText("Remove Employee");
        RemoveEmp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 255)));
        RemoveEmp.setFocusable(false);
        RemoveEmp.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        RemoveEmp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RemoveEmp.setVerifyInputWhenFocusTarget(false);
        RemoveEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RemoveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmpActionPerformed(evt);
            }
        });
        jPanel1.add(RemoveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 240, 50));

        jLabel9.setFont(new java.awt.Font("NTR", 3, 18)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 620, 20));

        clearbutton.setBackground(new java.awt.Color(51, 255, 255));
        clearbutton.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(0, 102, 102));
        clearbutton.setText("      Clear");
        clearbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 255)));
        clearbutton.setFocusable(false);
        clearbutton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        clearbutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        clearbutton.setVerifyInputWhenFocusTarget(false);
        clearbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 120, 50));

        jLabel10.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Salary");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 170, -1));

        SalaryField.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        SalaryField.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(SalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 630, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/managerbackground.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToLoginpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginpageActionPerformed
        // TODO add your handling code here:
        Login li=new Login();
        li.show();
        this.dispose();
    }//GEN-LAST:event_BackToLoginpageActionPerformed

    private void AddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddempActionPerformed
        // TODO add your handling code here:
        try{
         Connection con=DBConnection.getConnection();
           
        PreparedStatement ps1=null;
        ps1=con.prepareStatement("insert into employeeinfo values(?,?,?,?,?)");
        
        
        ps1.setString(1,UseridField.getText().trim());
        ps1.setString(2,NameField.getText().trim());
        ps1.setString(3,PasswordField.getText().trim());
        ps1.setString(4,AddressField.getText().trim());
        ps1.setInt(5,Integer.parseInt(SalaryField.getText().trim()));
        ps1.executeUpdate();
        jLabel5.setText("Employee added Successfully");
         con.close();
        }catch (Exception e){
           jLabel5.setText("Employee not added some error occured !");
        }
        
    }//GEN-LAST:event_AddempActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        ManagerLogin ml=new ManagerLogin();
        ml.show();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void removeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeIdActionPerformed

    private void RemoveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmpActionPerformed
        // TODO add your handling code here:
        try{
          Connection con=DBConnection.getConnection();
        Statement stmt=null;
        stmt=con.createStatement();
        String a=(removeId.getText().trim());
        stmt.executeUpdate("delete from employeeinfo where id ='"+a+"'");
       jLabel9.setText("Eemployee Removed Successfully");
       con.close();
        }catch(Exception e){
           jLabel9.setText("Employee not remove some error occured !");
        }
        
    }//GEN-LAST:event_RemoveEmpActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        UseridField.setText("");
        NameField.setText("");
       PasswordField.setText("");
       AddressField.setText("");
       jLabel5.setText("");
       SalaryField.setText("");
       removeId.setText("");
       jLabel9.setText("");
       
    }//GEN-LAST:event_clearbuttonActionPerformed

    /**
     * @param aErgs the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addempinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addempinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addempinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addempinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addempinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addemp;
    private javax.swing.JTextField AddressField;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackToLoginpage;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton RemoveEmp;
    private javax.swing.JTextField SalaryField;
    private javax.swing.JTextField UseridField;
    private javax.swing.JButton clearbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField removeId;
    // End of variables declaration//GEN-END:variables
}
