/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalbs;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author rohit157
 */
public class ManagerLogin extends javax.swing.JFrame {

    /**
     * Creates new form ManagerLogin
     */
    public ManagerLogin() {
        initComponents();
    }

    public void updateid() {
        if(newupdateField.getText().trim().equals("") && IdField.getText().trim().equals("") && PassField.getText().trim().equals("")){
           jLabel.setText("Please Fill the All Information in the Text Fields.");
        }
        else if(IdField.getText().trim().equals("") && PassField.getText().trim().equals("")){
            jLabel.setText("Enter ID and Password of Manager.");
        }
        else if(newupdateField.getText().trim().equals("") &&IdField.getText().trim().equals("")){
            jLabel.setText("Enter New Update Information and ID of Manager."); 
        }
        else if(newupdateField.getText().trim().equals("") &&PassField.getText().trim().equals("")){
            jLabel.setText("Enter New Update Information and Password of Manager."); 
        }
        else if (newupdateField.getText().trim().equals("")) {
                jLabel.setText("Enter the new Information For Manager.");
            } 
         else if(IdField.getText().trim().equals("")){
             jLabel.setText("Enter the Id of Manager !!!");
         }
         else if(PassField.getText().trim().equals("")){
             jLabel.setText("Enter the Password of Manager !!!");
         }
         else {
        try {
            Connection con = DBConnection.getConnection();
            int id = Integer.parseInt(IdField.getText().trim());
            String pass = PassField.getText().trim();

            PreparedStatement ps1 = null;

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT password FROM managerinfo where id=" + id);
            String dbpass = null;
           
                while (rs.next()) {
                    dbpass = rs.getString("password");
                }
                if (pass.equals(dbpass)) {

                    String cb = (String) jComboBox1.getSelectedItem();

                    if (cb.equals("NAME")) {

                        ps1 = con.prepareStatement("Update managerinfo set name=? where id=" + id);

                        ps1.setString(1, newupdateField.getText().trim());

                        ps1.executeUpdate();
                        jLabel.setText("Updated Manager Name.");

                    } else if (cb.equals("PASSWORD")) {
                        ps1 = con.prepareStatement("Update managerinfo set password=? where id=" + id);

                        ps1.setString(1, newupdateField.getText().trim());

                        ps1.executeUpdate();
                        jLabel.setText("Updated Manager Password.");

                    } else if (cb.equals("ADDRESS")) {
                        ps1 = con.prepareStatement("Update managerinfo set address=? where id=" + id);

                        ps1.setString(1, newupdateField.getText().trim());

                        ps1.executeUpdate();
                        jLabel.setText("Updated Manager Address.");

                    } else if (cb.equals("SALARY")) {
                        ps1 = con.prepareStatement("Update managerinfo set salary=? where id=" + id);

                        ps1.setInt(1, Integer.parseInt(newupdateField.getText().trim()));

                        ps1.executeUpdate();
                        jLabel.setText("Updated Manager Salary.");

                    } else {
                        ps1 = con.prepareStatement("Update managerinfo set id=? where id=" + id);

                        ps1.setInt(1, Integer.parseInt(newupdateField.getText().trim()));

                        ps1.executeUpdate();
                        jLabel.setText("Updated Manager ID.");

                    }

                } else {
                    jLabel.setText("Enter Manager Valid Password !");
                }
            

            }catch (Exception e) {
            jLabel.setText("Enter Valid ID Password of Manager !!!");
        }

        }
    }


        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddEmpbtn = new javax.swing.JButton();
        Logoutbtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        newupdateField = new javax.swing.JTextField();
        ManagerUpdatebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        PassField = new javax.swing.JTextField();
        Clearbtn = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        Stockbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Login");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddEmpbtn.setBackground(new java.awt.Color(0, 204, 204));
        AddEmpbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        AddEmpbtn.setForeground(new java.awt.Color(255, 0, 51));
        AddEmpbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/empaddbutton.png"))); // NOI18N
        AddEmpbtn.setText("Add Employee");
        AddEmpbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddEmpbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddEmpbtnMouseExited(evt);
            }
        });
        AddEmpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddEmpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 330, -1));

        Logoutbtn.setBackground(new java.awt.Color(0, 204, 204));
        Logoutbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 0, 51));
        Logoutbtn.setText("LOGOUT");
        Logoutbtn.setHideActionText(true);
        Logoutbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logoutbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseExited(evt);
            }
        });
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 190, 40));

        Updatebtn.setBackground(new java.awt.Color(0, 204, 204));
        Updatebtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 0, 51));
        Updatebtn.setText("Update Medicine Stock or Add");
        Updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdatebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdatebtnMouseExited(evt);
            }
        });
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 330, 50));

        jLabel2.setFont(new java.awt.Font("NTR", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("UPDATE MANAGER DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID ", "NAME", "PASSWORD", "ADDRESS", "SALARY" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans CJK KR", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 30));

        newupdateField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        newupdateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(newupdateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 250, 30));

        ManagerUpdatebtn.setBackground(new java.awt.Color(0, 204, 204));
        ManagerUpdatebtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        ManagerUpdatebtn.setForeground(new java.awt.Color(255, 0, 51));
        ManagerUpdatebtn.setText("UPDATE");
        ManagerUpdatebtn.setHideActionText(true);
        ManagerUpdatebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManagerUpdatebtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ManagerUpdatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManagerUpdatebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManagerUpdatebtnMouseExited(evt);
            }
        });
        ManagerUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerUpdatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(ManagerUpdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, 40));

        jLabel4.setFont(new java.awt.Font("NTR", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, -1));

        jLabel5.setFont(new java.awt.Font("NTR", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        IdField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        IdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 250, 30));

        PassField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        PassField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 250, 30));

        Clearbtn.setBackground(new java.awt.Color(0, 204, 204));
        Clearbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 0, 51));
        Clearbtn.setText("CLEAR");
        Clearbtn.setHideActionText(true);
        Clearbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clearbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Clearbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearbtnMouseExited(evt);
            }
        });
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 40));

        jLabel.setFont(new java.awt.Font("Noto Sans CJK KR", 1, 24)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 750, 30));

        Stockbtn.setBackground(new java.awt.Color(0, 204, 204));
        Stockbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Stockbtn.setForeground(new java.awt.Color(255, 0, 51));
        Stockbtn.setText("STOCK ");
        Stockbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StockbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StockbtnMouseExited(evt);
            }
        });
        Stockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Stockbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 330, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/managerbackground.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpbtnActionPerformed
        // TODO add your handling code here:
        Addempinfo aei = new Addempinfo();
        aei.show();
        this.dispose();
    }//GEN-LAST:event_AddEmpbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
        Login li = new Login();
        li.show();
        this.dispose();
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void AddEmpbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmpbtnMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(255, 255, 0);
        AddEmpbtn.setBackground(clr);

    }//GEN-LAST:event_AddEmpbtnMouseEntered

    private void AddEmpbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmpbtnMouseExited
        // TODO add your handling code here:
        Color clr = new Color(0, 204, 204);
        AddEmpbtn.setBackground(clr);
    }//GEN-LAST:event_AddEmpbtnMouseExited

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        Stock_update su = new Stock_update();
        su.show();
        this.dispose();
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void LogoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        Logoutbtn.setBackground(clr);

    }//GEN-LAST:event_LogoutbtnMouseEntered

    private void LogoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseExited
        Color clr = new Color(0, 204, 204);
        Logoutbtn.setBackground(clr);
    }//GEN-LAST:event_LogoutbtnMouseExited

    private void UpdatebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebtnMouseEntered
        Color clr = new Color(255, 255, 0);
        Updatebtn.setBackground(clr);
    }//GEN-LAST:event_UpdatebtnMouseEntered

    private void UpdatebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebtnMouseExited
        Color clr = new Color(0, 204, 204);
        Updatebtn.setBackground(clr);
    }//GEN-LAST:event_UpdatebtnMouseExited

    private void ManagerUpdatebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerUpdatebtnMouseEntered
        Color clr = new Color(255, 255, 0);
        ManagerUpdatebtn.setBackground(clr);
    }//GEN-LAST:event_ManagerUpdatebtnMouseEntered

    private void ManagerUpdatebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerUpdatebtnMouseExited
        Color clr = new Color(0, 204, 204);
        ManagerUpdatebtn.setBackground(clr);
    }//GEN-LAST:event_ManagerUpdatebtnMouseExited

    private void ManagerUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerUpdatebtnActionPerformed
        updateid();
    }//GEN-LAST:event_ManagerUpdatebtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String cb = (String) jComboBox1.getSelectedItem();

        if (cb.equals("NAME")) {

            jLabel3.setText("Enter New Name");
        } else if (cb.equals("PASSWORD")) {

            jLabel3.setText("Enter New Password");
        } else if (cb.equals("ADDRESS")) {

            jLabel3.setText("Enter New Address");
        } else if (cb.equals("SALARY")) {

            jLabel3.setText("Enter New Salary");
        } else {

            jLabel3.setText("Enter New ID");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ClearbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        Clearbtn.setBackground(clr);
    }//GEN-LAST:event_ClearbtnMouseEntered

    private void ClearbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearbtnMouseExited
        Color clr = new Color(0, 204, 204);
        Clearbtn.setBackground(clr);

    }//GEN-LAST:event_ClearbtnMouseExited

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        jLabel.setText("");
        jLabel.setText("");
        newupdateField.setText("");
        IdField.setText("");
        PassField.setText("");
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void StockbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseEntered
          Color clr = new Color(255, 255, 0);
        Stockbtn.setBackground(clr);
    }//GEN-LAST:event_StockbtnMouseEntered

    private void StockbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockbtnMouseExited
          Color clr = new Color(0, 204, 204);
        Stockbtn.setBackground(clr);

    }//GEN-LAST:event_StockbtnMouseExited

    private void StockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockbtnActionPerformed
        Stock s=new Stock();
        s.show();
        this.dispose();
    }//GEN-LAST:event_StockbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTextField IdField;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton ManagerUpdatebtn;
    private javax.swing.JTextField PassField;
    private javax.swing.JButton Stockbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newupdateField;
    // End of variables declaration//GEN-END:variables
}
