/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalbs;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohit157
 */
public class Stock_update extends javax.swing.JFrame {

    /**
     * Creates new form Stock_update
     */
    public Stock_update() {
        initComponents();
    }

    public void Deletemed() {
        try {
            Connection con = DBConnection.getConnection();
            Statement stmt = con.createStatement();
            int deleteid = Integer.parseInt(DeletemedIDField.getText().trim());

            PreparedStatement ps1 = null;
            ps1 = con.prepareStatement("DELETE FROM medicin_stock WHERE id = " + deleteid);

            ps1.executeUpdate();
            jLabel5.setText("Medicin Deleted Successfully");
            con.close();
        } catch (Exception e) {
            jLabel5.setText("Medicin  is not deleted some error occured !");
        }
    }

    public void updatemedstock() {
        try {
            Connection con = DBConnection.getConnection();
            Statement stmt = con.createStatement();
            int upid = Integer.parseInt(UpdateIdField.getText().trim());
            int upstock = Integer.parseInt(UpdateStockField.getText().trim());
            
          
          ResultSet rs=stmt.executeQuery("SELECT med_stock FROM medicin_stock where id="+upid);
            int stock=0;
          while (rs.next()) {                 
                 stock= rs.getInt("med_stock");
          }

            PreparedStatement ps1 = null;
            ps1 = con.prepareStatement("Update medicin_stock set med_stock=? where id=" + upid);
            upstock+=stock;
            ps1.setInt(1, upstock);

            ps1.executeUpdate();
            jLabel5.setText("Medicin Stock Updated Successfully");
            con.close();
        } catch (Exception e) {
            jLabel5.setText("Medicin Stock is not updated some error occured !");
        }
    }

    public void addmed() {
        try {
            Connection con = DBConnection.getConnection();

            PreparedStatement ps1 = null;
            ps1 = con.prepareStatement("insert into medicin_stock values(?,?,?,?,?)");

            int id = Integer.parseInt(IdField.getText().trim());
            int stock = Integer.parseInt(StockField.getText().trim());
            int price = Integer.parseInt(PriceField.getText().trim());

            ps1.setInt(1, id);
            ps1.setString(2, NameField.getText().trim());
            ps1.setInt(3, stock);
            ps1.setInt(4, price);
            ps1.setString(5, DescriptionField.getText().trim());
            ps1.executeUpdate();
            jLabel5.setText("Medicin added Successfully");
            con.close();
        } catch (Exception e) {
            jLabel5.setText("Medicin not added some error occured !");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        UpdateStockField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        StockField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        DescriptionField = new javax.swing.JTextField();
        UpdateIdField = new javax.swing.JTextField();
        AddStockbtn = new javax.swing.JButton();
        Clearbtn1 = new javax.swing.JButton();
        UpdateStockbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Clearbtn2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DeletemedIDField = new javax.swing.JTextField();
        DeleteMedbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("DESCRIPTION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 220, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 740, 30));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Delete Med ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 200, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 230, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("STOCK");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 230, -1));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("PRICE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel13.setText("UPDATE STOCK");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 290, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("ID");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, -1));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("STOCK");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, -1));

        IdField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        IdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 540, 30));

        UpdateStockField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        UpdateStockField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(UpdateStockField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 540, 30));

        PriceField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        PriceField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(PriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 540, 30));

        StockField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        StockField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(StockField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 540, 30));

        NameField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        NameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 540, 30));

        DescriptionField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        DescriptionField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(DescriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 540, 30));

        UpdateIdField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        UpdateIdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(UpdateIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 540, 30));

        AddStockbtn.setBackground(new java.awt.Color(0, 204, 204));
        AddStockbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        AddStockbtn.setForeground(new java.awt.Color(255, 0, 51));
        AddStockbtn.setText("ADD STOCK");
        AddStockbtn.setHideActionText(true);
        AddStockbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddStockbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AddStockbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddStockbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddStockbtnMouseExited(evt);
            }
        });
        AddStockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStockbtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddStockbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 210, 40));

        Clearbtn1.setBackground(new java.awt.Color(0, 204, 204));
        Clearbtn1.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Clearbtn1.setForeground(new java.awt.Color(255, 0, 51));
        Clearbtn1.setText("CLEAR");
        Clearbtn1.setHideActionText(true);
        Clearbtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clearbtn1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Clearbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clearbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clearbtn1MouseExited(evt);
            }
        });
        Clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clearbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Clearbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 210, 40));

        UpdateStockbtn.setBackground(new java.awt.Color(0, 204, 204));
        UpdateStockbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        UpdateStockbtn.setForeground(new java.awt.Color(255, 0, 51));
        UpdateStockbtn.setText(" UPDATE STOCK");
        UpdateStockbtn.setHideActionText(true);
        UpdateStockbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UpdateStockbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        UpdateStockbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateStockbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UpdateStockbtnMouseExited(evt);
            }
        });
        UpdateStockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStockbtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateStockbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 210, 40));

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Delete Medicine");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 290, -1));

        Clearbtn2.setBackground(new java.awt.Color(0, 204, 204));
        Clearbtn2.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Clearbtn2.setForeground(new java.awt.Color(255, 0, 51));
        Clearbtn2.setText("CLEAR");
        Clearbtn2.setHideActionText(true);
        Clearbtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clearbtn2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Clearbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Clearbtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Clearbtn2MouseExited(evt);
            }
        });
        Clearbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clearbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(Clearbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 210, 40));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel17.setText("ADD STOCK");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 290, -1));

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 230, -1));

        DeletemedIDField.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        DeletemedIDField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jPanel1.add(DeletemedIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 50, 30));

        DeleteMedbtn.setBackground(new java.awt.Color(0, 204, 204));
        DeleteMedbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        DeleteMedbtn.setForeground(new java.awt.Color(255, 0, 51));
        DeleteMedbtn.setText("Delete Medicin");
        DeleteMedbtn.setHideActionText(true);
        DeleteMedbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeleteMedbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        DeleteMedbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMedbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMedbtnMouseExited(evt);
            }
        });
        DeleteMedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMedbtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteMedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 210, 40));

        Backbtn.setBackground(new java.awt.Color(0, 204, 204));
        Backbtn.setFont(new java.awt.Font("NTR", 3, 24)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 0, 51));
        Backbtn.setText("BACK");
        Backbtn.setHideActionText(true);
        Backbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Backbtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackbtnMouseExited(evt);
            }
        });
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalbs/src_img/managerbackground.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStockbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStockbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        AddStockbtn.setBackground(clr);

    }//GEN-LAST:event_AddStockbtnMouseEntered

    private void AddStockbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStockbtnMouseExited
        Color clr = new Color(0, 204, 204);
        AddStockbtn.setBackground(clr);
    }//GEN-LAST:event_AddStockbtnMouseExited

    private void AddStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStockbtnActionPerformed
        addmed();
    }//GEN-LAST:event_AddStockbtnActionPerformed

    private void Clearbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clearbtn1MouseEntered
        Color clr = new Color(255, 255, 0);
        Clearbtn1.setBackground(clr);
    }//GEN-LAST:event_Clearbtn1MouseEntered

    private void Clearbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clearbtn1MouseExited
        Color clr = new Color(0, 204, 204);
        Clearbtn1.setBackground(clr);
    }//GEN-LAST:event_Clearbtn1MouseExited

    private void Clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clearbtn1ActionPerformed
        IdField.setText("");
        NameField.setText("");
        StockField.setText("");
        PriceField.setText("");
        DescriptionField.setText("");
        jLabel5.setText("");
        DeletemedIDField.setText("");
    }//GEN-LAST:event_Clearbtn1ActionPerformed

    private void UpdateStockbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStockbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        UpdateStockbtn.setBackground(clr);
    }//GEN-LAST:event_UpdateStockbtnMouseEntered

    private void UpdateStockbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStockbtnMouseExited
        Color clr = new Color(0, 204, 204);
        UpdateStockbtn.setBackground(clr);
    }//GEN-LAST:event_UpdateStockbtnMouseExited

    private void UpdateStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStockbtnActionPerformed
        updatemedstock();
    }//GEN-LAST:event_UpdateStockbtnActionPerformed

    private void Clearbtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clearbtn2MouseEntered
        Color clr = new Color(255, 255, 0);
        Clearbtn2.setBackground(clr);
    }//GEN-LAST:event_Clearbtn2MouseEntered

    private void Clearbtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clearbtn2MouseExited
        Color clr = new Color(0, 204, 204);
        Clearbtn2.setBackground(clr);
    }//GEN-LAST:event_Clearbtn2MouseExited

    private void Clearbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clearbtn2ActionPerformed
        UpdateIdField.setText("");
        UpdateStockField.setText("");
        jLabel5.setText("");
        DeletemedIDField.setText("");
    }//GEN-LAST:event_Clearbtn2ActionPerformed

    private void DeleteMedbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMedbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        DeleteMedbtn.setBackground(clr);
    }//GEN-LAST:event_DeleteMedbtnMouseEntered

    private void DeleteMedbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMedbtnMouseExited
        Color clr = new Color(0, 204, 204);
        DeleteMedbtn.setBackground(clr);
    }//GEN-LAST:event_DeleteMedbtnMouseExited

    private void DeleteMedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMedbtnActionPerformed
        Deletemed();
    }//GEN-LAST:event_DeleteMedbtnActionPerformed

    private void BackbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseEntered
        Color clr = new Color(255, 255, 0);
        Backbtn.setBackground(clr);
    }//GEN-LAST:event_BackbtnMouseEntered

    private void BackbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseExited
       Color clr = new Color(0, 204, 204);
        Backbtn.setBackground(clr);
    }//GEN-LAST:event_BackbtnMouseExited

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
      ManagerLogin ml=new ManagerLogin();
      ml.show();
      this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStockbtn;
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Clearbtn1;
    private javax.swing.JButton Clearbtn2;
    private javax.swing.JButton DeleteMedbtn;
    private javax.swing.JTextField DeletemedIDField;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JTextField IdField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JTextField StockField;
    private javax.swing.JTextField UpdateIdField;
    private javax.swing.JTextField UpdateStockField;
    private javax.swing.JButton UpdateStockbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
