/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalbs;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;


/**
 *
 * @author rohit157
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    DefaultTableModel model;
    public int grandtotal = 0;

    public Stock() {
        initComponents();
    }
    
    

    public String setEmpname() {
        Login lg = new Login();
        String username = lg.username;
        return username;
    }

    public String setDate() {
        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("EEEE dd MMMM yyyy");
        String strDate = dateFormat.format(date);
        return strDate;
    }

    public String setTime() {

        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("hh:mm:ss");
        String strTime = dateFormat.format(date);

        return strTime;

    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) StockTable.getModel();
        model.setRowCount(0);
    }

    public void avilablestocktable() {
        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from medicin_stock");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                int med_ID = rs.getInt("id");
                String med_Name = rs.getString("med_name");
                int med_Quantity = rs.getInt("med_stock");
                int med_Price = rs.getInt("med_price");
                Object[] obj = {med_ID, med_Name, med_Quantity, med_Price};
                model = (DefaultTableModel) StockTable.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    
  
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Refreshbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        Logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedicalBS");
        setBackground(new java.awt.Color(0, 255, 255));
        setMinimumSize(new java.awt.Dimension(1580, 860));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Refreshbtn.setBackground(new java.awt.Color(255, 0, 153));
        Refreshbtn.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        Refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        Refreshbtn.setText("Refresh");
        Refreshbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefreshbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefreshbtnMouseExited(evt);
            }
        });
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 190, 40));

        StockTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        StockTable.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "NAME", "QUANTITY", "PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        StockTable.setAlignmentX(0.0F);
        StockTable.setName(""); // NOI18N
        jScrollPane1.setViewportView(StockTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 1070, 370));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText("STOCK IN MEDICAL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 290, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("Time :");
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, 40));

        TimeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        TimeLabel.setFocusable(false);
        TimeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TimeLabel.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(TimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 340, 40));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 153));
        jLabel13.setText("Date :");
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, 40));

        DateLabel.setFont(new java.awt.Font("Liberation Sans", 3, 30)); // NOI18N
        DateLabel.setText(setDate());
        jPanel1.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 520, 40));

        Logoutbtn.setBackground(new java.awt.Color(255, 0, 153));
        Logoutbtn.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn.setText("BACK");
        Logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutbtnMouseExited(evt);
            }
        });
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshbtnMouseEntered
        Color clr = new Color(255, 0, 51);
        Refreshbtn.setBackground(clr);
    }//GEN-LAST:event_RefreshbtnMouseEntered

    private void RefreshbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshbtnMouseExited
        Color clr = new Color(255, 0, 153);
        Refreshbtn.setBackground(clr);
    }//GEN-LAST:event_RefreshbtnMouseExited

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed
        clearTable();
        avilablestocktable();
        TimeLabel.setText(setTime());

    }//GEN-LAST:event_RefreshbtnActionPerformed

    private void LogoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseEntered
        Color clr = new Color(255, 0, 51);
        Logoutbtn.setBackground(clr);
    }//GEN-LAST:event_LogoutbtnMouseEntered

    private void LogoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutbtnMouseExited
        Color clr = new Color(255, 0, 153);
        Logoutbtn.setBackground(clr);
    }//GEN-LAST:event_LogoutbtnMouseExited

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
       ManagerLogin ml=new ManagerLogin();
       ml.show();
        this.dispose();

    }//GEN-LAST:event_LogoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Stock().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JTable StockTable;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
